-- Create the transactions table
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  description text not null,
  amount numeric not null,
  type text check (type in ('income', 'expense')) not null,
  date date not null,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table transactions enable row level security;

-- Create policies
create policy "Users can view their own transactions"
  on transactions for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own transactions"
  on transactions for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own transactions"
  on transactions for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own transactions"
  on transactions for delete
  using ( auth.uid() = user_id );
